spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ducthinh1
#    url: jdbc:postgresql://localhost:5432/d2hlp6ainokaif
#    username: jigclkeeswxyse
#    password: a7dcbb25e84eb0dc2fe4764e0c9d05e48b5ede420cd2dd3c33c3d649636e99e4
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
blog:
  title: Thịnh đây
  banner:
    title: Mỗi ngày lớn lên
    content: Khi lớn lên rồi, tôi mới nhận ra mình không còn nhỏ nữa
server:
  port: 9002